-- MySQL Script generated by MySQL Workbench
-- sáb 09 abr 2016 08:20:50 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema matricula
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema matricula
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matricula` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `matricula` ;

-- -----------------------------------------------------
-- Table `matricula`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`estudiante` (
  `idestudiante` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  `programa` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idestudiante`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matricula`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`materia` (
  `idmateria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `creditos` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idmateria`)  COMMENT '')
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `matricula`.`estudiante_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`estudiante_materia` (
  `estudiante_idestudiante` INT NOT NULL COMMENT '',
  `materia_idmateria` INT NOT NULL COMMENT '',
  PRIMARY KEY (`estudiante_idestudiante`, `materia_idmateria`)  COMMENT '',
  INDEX `fk_estudiante_has_materia_materia1_idx` (`materia_idmateria` ASC)  COMMENT '',
  INDEX `fk_estudiante_has_materia_estudiante_idx` (`estudiante_idestudiante` ASC)  COMMENT '',
  CONSTRAINT `fk_estudiante_has_materia_estudiante`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `matricula`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_has_materia_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `matricula`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matricula`.`constancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`constancia` (
  `idconstancia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `semestre` INT(5) NOT NULL COMMENT '',
  `idestudiante` INT NOT NULL COMMENT '',
  `fecha` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`idconstancia`, `idestudiante`)  COMMENT '',
  INDEX `idestudiante_idx` (`idestudiante` ASC)  COMMENT '',
  CONSTRAINT `idestudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `matricula`.`estudiante` (`idestudiante`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
